#!/bin/bash

# Quick commands to enable kiosk mode on the touchscreen
echo "🖥️ ShackMate Touchscreen Kiosk Mode Setup"
echo "========================================"
echo ""
echo "The touchscreen is showing the terminal because we need to:"
echo "1. Install X11 and Chromium on the Pi (not in Docker)"
echo "2. Configure auto-start of the graphical interface"
echo "3. Launch Chromium directly on the Pi's display"
echo ""
echo "💡 Quick Fix Commands (run on the Pi):"
echo ""
echo "ssh sm@10.146.1.254"
echo ""
echo "# Install display packages"
echo "sudo apt-get update"
echo "sudo apt-get install -y xinit xorg chromium-browser unclutter"
echo ""
echo "# Create startup script"
echo 'cat > ~/.xinitrc << "EOF"'
echo "#!/bin/bash"
echo "xset s off; xset -dpms; xset s noblank"
echo "unclutter -idle 0.5 -root &"
echo "sleep 5"
echo "cd ~/docker && docker-compose up -d"
echo "sleep 10"
echo "chromium-browser --kiosk --no-sandbox --disable-gpu http://localhost"
echo "EOF"
echo ""
echo "chmod +x ~/.xinitrc"
echo ""
echo "# Modify auto-login to start X"
echo 'echo "if [[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]]; then exec startx; fi" >> ~/.bashrc'
echo ""
echo "# Reboot to activate"
echo "sudo reboot"
echo ""
echo "🎯 After reboot, the touchscreen should show the ShackMate interface!"
