#!/bin/bash

# Manual Commands to Fix Apache on Raspberry Pi
# Run these commands after SSHing to the Pi

echo "🔧 ShackMate Apache Fix - Manual Commands"
echo "========================================"
echo ""
echo "1️⃣ First, SSH to your Raspberry Pi:"
echo "   ssh sm@10.146.1.254"
echo ""
echo "2️⃣ Then run these commands on the Pi:"
echo ""
echo "# Stop current containers"
echo "cd ~/docker"
echo "docker-compose down"
echo ""
echo "# Download the latest fixed configuration"
echo "curl -o docker-compose.yml https://raw.githubusercontent.com/ShackMate/ShackMate-HMI/main/docker/docker-compose.yml"
echo "curl -o Dockerfile https://raw.githubusercontent.com/ShackMate/ShackMate-HMI/main/docker/Dockerfile"
echo "curl -o supervisord.conf https://raw.githubusercontent.com/ShackMate/ShackMate-HMI/main/docker/supervisord.conf"
echo "curl -o entrypoint.sh https://raw.githubusercontent.com/ShackMate/ShackMate-HMI/main/docker/entrypoint.sh"
echo ""
echo "# Make scripts executable"
echo "chmod +x entrypoint.sh"
echo ""
echo "# Rebuild and start containers with fixes"
echo "docker-compose up -d --build"
echo ""
echo "# Check if Apache is working"
echo "sleep 10"
echo "curl -s http://localhost && echo 'Apache is working!' || echo 'Apache still not working'"
echo ""
echo "# Check Chromium status"
echo "docker-compose exec shackmate-hmi pgrep chromium && echo 'Chromium is running' || echo 'Chromium not running'"
echo ""
echo "🎯 The key changes made:"
echo "   - Removed failing SMB services (nmbd/smbd)"
echo "   - Added Apache configuration fixes"
echo "   - Improved container startup process"
echo "   - Better error handling"
